AllCops:
  Exclude:
    - 'vendor/**/*'
  RunRailsCops: true
  DisplayCopNames: true

Style/AsciiComments:
    Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

LineLength:
  Enabled: false

Style/AlignHash:
  Enabled: false
