# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b21c5fb942eb057bde31c59ec46988f31809de8006f54297a3517d6c8dbdd9af31579d83a280a3157d4d58b478bb85f6231c4cc964d8b209509b61b45c3312

test:
  secret_key_base: 611a7394b0aea9823ff8b92cac64d7a88f008b38b3577c2f3bbe7117f4660db85a8cd717145d219a45a5fc45b0f198d26bffcc3db44b15237dfe8db4294dee8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
